### ISSUE TITLE
Project sign-up for finrod

### ISSUE THREAD

**Issue by yungyuc** [yungyuc/r_finrod#1]
For project collaborators to sign up.

**Comment by yyniu007** [comment]
touchdown

**Comment by yungyuc** [comment]
@yyniu007 always!  And don't forget to pick a good-looking avatar for yourself.

**Comment by b483124** [comment]
Touchdown

**Comment by yungyuc** [comment]
@b483124 great!  This team seemed to make me defenseless on offense.

**Comment by yungyuc** [comment]
@yyniu007 @b483124 please watch this project.  Once successful, you'll see yourselves in https://github.com/yungyuc/r_finrod/watchers .

**Comment by tai271828** [comment]
I'm in ;)

**Comment by yyniu007** [comment]
PLease introduce your background and current position:  I am a professor at Aerospace Engineering, TKU.

@yungyuc  if  we upload our inviscid two-fluid code. What benefit we can improve our code to be with visvous effects and chemistry form  the current envirnment.

**Comment by yungyuc** [comment]
This is Yung-Yu, the author of SOLVCON and an enthusiast for Python, HPC, and conservation laws.

@yyniu007 The benefit is collaboration and code quality.  Version control is the most basic thing for software development.  Any serious software is built upon it before it can be developed among a team.  Without rigorous version control, one doesn't know what is changed, and how and when it is changed.  Git is the version control system we'll be using.

On top of that we'll practice code review and higher-order engineering to make code more robust, easier to be changed, and higher-performance.  It may take years to get there.  The ultimate form may be incorporation to SOLVCON.  SOLVCON has undergone the engineering process many years ago, and instead of redoing everything, it's only logical to reuse and reinforce the existing framework.  However, if your code isn't treated with the most basic engineering, it won't fit in the framework.

The first step is to open-source your code.  I'd recommed to use a BSD license, which freely allows everyone on the planet to use your code to do anything, making or not making money.  Some people opt to a "copyleft" license (GPL) to make users hard to make money from it, and I don't see it as a very efficient model for scientific computing.  The point of open source is for productivity.  Without the constraint to "protect" the code, we may do almost anything with the code and that makes life easy.  And, although all the software engineering practices may be applied to open- or close-source software development, I have zero interest in developing close-source software in my free time, for I have been doing exactly that in my day job.

All the explanation may sound remote for now.  Without practicing it, and maybe for years, one doesn't fully understand the benefits.

**Comment by tai271828** [comment]
This is Taihsiang, one of the contributor of SOLVCON, and an enthusiast for [free/libre software](https://en.wikipedia.org/wiki/Free_software). I am good at Linux operation system and I could help the part of software engineering and infrastructure of this project. Looking forward to having fun in Project Finrod.

**Comment by yungyuc** [comment]
Everyone's onboard.  Since @b483124 hasn't written the introduction, I'll leave this ticket open for a while.  I'll close it next time I check it.

**Comment by b483124** [comment]
This is Yu-Chieh Chen, the second grade of master's student for Dr.Niu at
Aerospace Engineering, TKU.

2017-12-16 7:00 GMT+08:00 Yung-Yu Chen <notifications@github.com>:
